---
watch:
  - src
  - .trmnlp.yml

custom_fields:
  anrede: männlich

time_zone: Europe/Berlin

variables:
  trmnl:
    user:
      name: Robert
    plugin_settings:
      instance_name: Hedgehog Fit
